CREATE DATABASE QLSV_NT
GO

USE QLSV_NT
GO

CREATE TABLE SINHVIEN (
	ID INT NOT NULL,
	IDTAIKHOAN INT NOT NULL,
	IDNGANHHOC INT NOT NULL,
	MSSV NVARCHAR(10) NOT NULL,
	EMAIL NVARCHAR(16) NOT NULL,
	TRANGTHAI NVARCHAR(10),

	CONSTRAINT PK_SINHVIEN PRIMARY KEY(ID),

	CONSTRAINT FK_SINHVIEN_NGANHHOC FOREIGN KEY(IDNGANHHOC) REFERENCES NGANHHOC(ID),
	CONSTRAINT FK_SINHVIEN_TAIKHOAN FOREIGN KEY(IDTAIKHOAN) REFERENCES TAIKHOAN(ID),
)
GO

CREATE TABLE NHANTHAN(
	ID INT NOT NULL,
	TEN NVARCHAR(25) NOT NULL,
	TUOI INT NOT NULL,
	SDT NVARCHAR(11) NOT NULL,
	DIACHI NVARCHAR(30) NOT NULL,

	CONSTRAINT PK_NHANTHAN PRIMARY KEY(ID)
)
GO

CREATE TABLE SINHVIEN_NHANTHAN(
	IDNHANTHAN INT NOT NULL,
	IDSINHVIEN INT NOT NULL,

	CONSTRAINT PK_SINHVIEN_NHANTHAN PRIMARY KEY(IDNHANTHAN,IDSINHVIEN),
	
	CONSTRAINT FK_SINHVIEN_NHANTHAN_NT FOREIGN KEY(IDNHANTHAN) REFERENCES NHANTHAN(ID),
	CONSTRAINT FK_SINHVIEN_NHANTHAN_SV FOREIGN KEY(IDSINHVIEN) REFERENCES SINHVIEN(ID),
)
GO

CREATE TABLE NGANHHOC(
	ID INT NOT NULL,
	MANGANH NVARCHAR(30) NOT NULL,
	TENNGANH NVARCHAR(30) NOT NULL,

	CONSTRAINT PK_NGANHHOC PRIMARY KEY(ID),
)
GO

CREATE TABLE TAIKHOAN(
	ID INT NOT NULL,
	TEN NVARCHAR(30) NOT NULL,
	TUOI INT NOT NULL,
	SDT NVARCHAR(11) NOT NULL,
	DIACHI NVARCHAR(30) NOT NULL,

	CONSTRAINT PK_TAIKHOAN PRIMARY KEY(ID),
)
select * from NGANHHOC
insert into SINHVIEN(IDTAIKHOAN,IDNGANHHOC,MSSV,EMAIL,TRANGTHAI)
values (2,13,'ph12221','sangbxph12221','null')
insert into TAIKHOAN(TEN,TUOI,SDT,DIACHI)
values ('SANG',17,'123456789','Ha Noi')